# Generated by Django 5.0.7 on 2024-08-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('imgen_proyecto', models.ImageField(null=True, upload_to='imagenes/')),
                ('nombre_propiedad', models.CharField(blank=True, max_length=255, null=True, verbose_name='nombre propiedad')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('codigo_interno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código Interno')),
                ('cantidad_niveles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cantidad de Niveles')),
                ('condicion_estado', models.CharField(max_length=50, verbose_name='Condición / Estado')),
                ('estilo', models.CharField(max_length=50, verbose_name='Estilo')),
                ('propiedad_exclusiva', models.BooleanField(default=False, verbose_name='¿Propiedad Exclusiva?')),
                ('propiedad_destacada', models.BooleanField(default=False, verbose_name='¿Propiedad Destacada?')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('estado_provincia', models.CharField(max_length=100, verbose_name='Estado/ Provincia')),
                ('ciudad_delegacion', models.CharField(max_length=100, verbose_name='Ciudad/ Delegación')),
                ('direccion1', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 1')),
                ('direccion2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección 2')),
                ('monto_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Monto de Venta')),
                ('monto_brokers', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Monto Para Brokers')),
                ('facilidades_comunes', models.JSONField(blank=True, null=True, verbose_name='Facilidades Comunes')),
                ('facilidades_electricas', models.JSONField(blank=True, null=True, verbose_name='Facilidades Eléctricas')),
                ('exterior', models.JSONField(blank=True, null=True, verbose_name='Exterior')),
                ('general', models.JSONField(blank=True, null=True, verbose_name='General')),
                ('interior', models.JSONField(blank=True, null=True, verbose_name='Interior')),
                ('politicas', models.JSONField(blank=True, null=True, verbose_name='Políticas')),
                ('ubicacion', models.JSONField(blank=True, null=True, verbose_name='Ubicación')),
                ('construccion', models.JSONField(blank=True, null=True, verbose_name='Construcción')),
            ],
        ),
    ]
